name: Build LaTeX Document
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-latex-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Save result
        uses: actions/upload-artifact@v2.2.3
        with:
          name: document
          path: main.pdf
