name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Compile document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Rename document
        run: mv main.pdf buku-kp.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: document
          path: buku-kp.pdf
